# Generated by Django 3.2.3 on 2021-06-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('author', models.TextField(default='')),
                ('epoch', models.TextField(default='')),
                ('genre', models.TextField(default='')),
            ],
        ),
    ]
