# Generated by Django 3.2.3 on 2021-06-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_library', '0002_bookshelf_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(default=None)),
                ('user_id', models.IntegerField(default=None)),
                ('check_out_date', models.DateTimeField(auto_now_add=True)),
                ('planned_date_of_return', models.DateTimeField()),
                ('date_of_return', models.DateTimeField()),
                ('status', models.TextField(default='Active')),
            ],
        ),
    ]
