# Generated by Django 3.2.3 on 2021-06-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_library', '0004_auto_20210607_2214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rental_list',
            new_name='RentalList',
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='quantity',
            field=models.IntegerField(default=6),
        ),
    ]
