# Generated by Django 3.2.3 on 2021-06-08 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_library', '0006_auto_20210608_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='quantity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='rentallist',
            name='book_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main_library.bookshelf'),
        ),
        migrations.AlterField(
            model_name='rentallist',
            name='date_of_return',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rentallist',
            name='planned_date_of_return',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
