# Generated by Django 3.2.3 on 2021-06-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_library', '0007_auto_20210608_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
