# Generated by Django 3.2.3 on 2021-06-11 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_library', '0008_alter_bookshelf_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='quantity',
            field=models.IntegerField(default=7),
        ),
        migrations.CreateModel(
            name='BooksNotAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main_library.bookshelf')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
